#!/bin/bash

lex=`cat $1 | ./lexer/analizator/analizator`
if [[ $? -ne 0 ]]; then exit 1; fi

syn=`echo "$lex" | ./syntax/analizator/analizator`
if [[ $? -ne 0 ]]; then exit 1; fi

asm=`echo "$syn" | ./codegen/codegen`
if [[ $? -ne 0 ]]; then exit 1; fi

echo "$asm" | node frisc/main.js 2>&1 | tail -1
